//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34011
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34011.
// 
#pragma warning disable 1591

namespace PresentationLayer.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetEstudianteByCIOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEstudiantesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::PresentationLayer.Properties.Settings.Default.PresentationLayer_localhost_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetEstudianteByCICompletedEventHandler GetEstudianteByCICompleted;
        
        /// <remarks/>
        public event GetEstudiantesCompletedEventHandler GetEstudiantesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEstudianteByCI", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Estudiante GetEstudianteByCI(string ci) {
            object[] results = this.Invoke("GetEstudianteByCI", new object[] {
                        ci});
            return ((Estudiante)(results[0]));
        }
        
        /// <remarks/>
        public void GetEstudianteByCIAsync(string ci) {
            this.GetEstudianteByCIAsync(ci, null);
        }
        
        /// <remarks/>
        public void GetEstudianteByCIAsync(string ci, object userState) {
            if ((this.GetEstudianteByCIOperationCompleted == null)) {
                this.GetEstudianteByCIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEstudianteByCIOperationCompleted);
            }
            this.InvokeAsync("GetEstudianteByCI", new object[] {
                        ci}, this.GetEstudianteByCIOperationCompleted, userState);
        }
        
        private void OnGetEstudianteByCIOperationCompleted(object arg) {
            if ((this.GetEstudianteByCICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEstudianteByCICompleted(this, new GetEstudianteByCICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEstudiantes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetEstudiantes() {
            object[] results = this.Invoke("GetEstudiantes", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetEstudiantesAsync() {
            this.GetEstudiantesAsync(null);
        }
        
        /// <remarks/>
        public void GetEstudiantesAsync(object userState) {
            if ((this.GetEstudiantesOperationCompleted == null)) {
                this.GetEstudiantesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEstudiantesOperationCompleted);
            }
            this.InvokeAsync("GetEstudiantes", new object[0], this.GetEstudiantesOperationCompleted, userState);
        }
        
        private void OnGetEstudiantesOperationCompleted(object arg) {
            if ((this.GetEstudiantesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEstudiantesCompleted(this, new GetEstudiantesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Estudiante {
        
        private string ciField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private string carreraField;
        
        private int numeroCreditosField;
        
        private string emailField;
        
        private string claveField;
        
        private string generoField;
        
        private bool creditosMallaField;
        
        private bool idiomasField;
        
        private bool cCFFField;
        
        private bool practicasField;
        
        private bool vinculacionField;
        
        private bool valoresPagadosField;
        
        /// <comentarios/>
        public string CI {
            get {
                return this.ciField;
            }
            set {
                this.ciField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
            }
        }
        
        /// <comentarios/>
        public string Carrera {
            get {
                return this.carreraField;
            }
            set {
                this.carreraField = value;
            }
        }
        
        /// <comentarios/>
        public int NumeroCreditos {
            get {
                return this.numeroCreditosField;
            }
            set {
                this.numeroCreditosField = value;
            }
        }
        
        /// <comentarios/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <comentarios/>
        public string Clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
            }
        }
        
        /// <comentarios/>
        public string Genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
            }
        }
        
        /// <comentarios/>
        public bool CreditosMalla {
            get {
                return this.creditosMallaField;
            }
            set {
                this.creditosMallaField = value;
            }
        }
        
        /// <comentarios/>
        public bool Idiomas {
            get {
                return this.idiomasField;
            }
            set {
                this.idiomasField = value;
            }
        }
        
        /// <comentarios/>
        public bool CCFF {
            get {
                return this.cCFFField;
            }
            set {
                this.cCFFField = value;
            }
        }
        
        /// <comentarios/>
        public bool Practicas {
            get {
                return this.practicasField;
            }
            set {
                this.practicasField = value;
            }
        }
        
        /// <comentarios/>
        public bool Vinculacion {
            get {
                return this.vinculacionField;
            }
            set {
                this.vinculacionField = value;
            }
        }
        
        /// <comentarios/>
        public bool ValoresPagados {
            get {
                return this.valoresPagadosField;
            }
            set {
                this.valoresPagadosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetEstudianteByCICompletedEventHandler(object sender, GetEstudianteByCICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEstudianteByCICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEstudianteByCICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Estudiante Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Estudiante)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetEstudiantesCompletedEventHandler(object sender, GetEstudiantesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEstudiantesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEstudiantesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591